name: Build Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coder-node:
    name: Build coder-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: coder-node
          tags: ghcr.io/${{ github.actor }}/coder-node:latest
          cache-from: type=gha,scope=coder-node
          cache-to: type=gha,mode=max,scope=coder-node

  coder-mariadb:
    name: Build coder-mariadb
    runs-on: ubuntu-latest
    needs: 'coder-node'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: coder-mariadb
          tags: ghcr.io/${{ github.actor }}/coder-mariadb:latest
          cache-from: type=gha,scope=coder-mariadb
          cache-to: type=gha,mode=max,scope=coder-mariadb
