name: Build Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile

concurrency:
  group: ci-tests-${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  build:
    name: Build minecraft-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: minecraft-server
          tags: ghcr.io/${{ github.actor }}/minecraft-server:latest
          cache-from: type=gha,scope=minecraft-server
          cache-to: type=gha,mode=max,scope=minecraft-server
